#!/usr/bin/env python3
"""
Reeleezee File Downloader.

Downloads all available document files from Reeleezee:
- Purchase invoice scans (original JPG/PDF uploads)
- Sales invoice PDFs (generated by Reeleezee)
- Offering/quote PDFs (generated by Reeleezee)

Files are organized by type and year with a metadata index.

Usage:
    reeleezee-download --username USER --password PASS
    reeleezee-download --username USER --password PASS --output-dir ./files
    reeleezee-download  # reads credentials from .env file
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict

from .client import ReeleezeeClient


def _load_env():
    """Load environment variables from .env file if available."""
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass


class ReeleezeeFileDownloader:
    """Downloads all document files from Reeleezee.

    Iterates over purchase invoice scans, sales invoices, and offerings,
    downloading the associated files and organizing them by type and year.
    """

    def __init__(self, client: ReeleezeeClient):
        """Initialize with an authenticated API client.

        Args:
            client: An authenticated ReeleezeeClient instance.
        """
        self.client = client
        self.admin_id = client.administrations[0]["id"]
        self.admin_name = client.administrations[0].get("Name", "unknown")

    def download_all(self, output_dir: str):
        """Download all files organized by type.

        Args:
            output_dir: Base directory for downloaded files.
        """
        base_dir = Path(output_dir)
        base_dir.mkdir(parents=True, exist_ok=True)

        start_time = time.time()
        stats = {
            "purchase_scans": 0, "sales_pdfs": 0, "offering_pdfs": 0,
            "errors": 0, "total_bytes": 0,
        }

        self._download_purchase_scans(base_dir, stats)
        self._download_sales_invoices(base_dir, stats)
        self._download_offerings(base_dir, stats)

        elapsed = time.time() - start_time
        total_mb = stats["total_bytes"] / (1024 * 1024)

        print(f"\n{'=' * 60}")
        print(f"Download complete in {elapsed:.0f}s")
        print(f"  Purchase invoice scans: {stats['purchase_scans']}")
        print(f"  Sales invoice PDFs:     {stats['sales_pdfs']}")
        print(f"  Offering PDFs:          {stats['offering_pdfs']}")
        print(f"  Errors:                 {stats['errors']}")
        print(f"  Total size:             {total_mb:.1f} MB")
        print(f"  Output:                 {base_dir}")
        print(f"{'=' * 60}")

    def _safe_filename(self, name: str) -> str:
        """Create a filesystem-safe filename."""
        return "".join(c if c.isalnum() or c in ".-_ " else "_" for c in name)

    def _download_purchase_scans(self, base_dir: Path, stats: Dict):
        """Download all purchase invoice scans organized by year."""
        print(f"\n{'=' * 60}")
        print("Downloading purchase invoice scans...")
        print(f"{'=' * 60}")

        scans = self.client.get_paginated(f"{self.admin_id}/PurchaseInvoiceScans")
        print(f"  Found {len(scans)} scans")

        scans_dir = base_dir / "purchase_invoice_scans"
        scans_dir.mkdir(exist_ok=True)

        metadata = []
        downloaded = 0
        errors = 0

        for i, scan in enumerate(scans, 1):
            scan_id = scan["id"]
            filename = scan.get("FileName", f"{scan_id}.bin")
            date = scan.get("Date", "")
            year = date[:4] if date else "unknown"
            date_short = date[:10] if date else "unknown"

            year_dir = scans_dir / year
            year_dir.mkdir(exist_ok=True)

            safe_name = self._safe_filename(filename)
            dest_file = year_dir / f"{date_short}_{safe_name}"

            # Skip already downloaded files
            if dest_file.exists() and dest_file.stat().st_size > 0:
                metadata.append({
                    "id": scan_id, "filename": filename, "date": date,
                    "saved_as": str(dest_file.relative_to(base_dir)),
                    "status": "skipped_exists",
                })
                downloaded += 1
                continue

            content = self.client.download(f"{self.admin_id}/Files/{scan_id}/Download")

            if content:
                dest_file.write_bytes(content)
                downloaded += 1
                stats["total_bytes"] += len(content)
                metadata.append({
                    "id": scan_id, "filename": filename, "date": date,
                    "size_bytes": len(content),
                    "saved_as": str(dest_file.relative_to(base_dir)),
                    "status": "downloaded",
                })
                if i % 50 == 0 or i == len(scans):
                    print(f"    [{i}/{len(scans)}] {downloaded} downloaded, {errors} errors")
            else:
                errors += 1
                metadata.append({
                    "id": scan_id, "filename": filename, "date": date,
                    "saved_as": None, "status": "error",
                })

        self._save_index(scans_dir, "purchase_invoice_scans", len(scans),
                         downloaded, errors, metadata)
        stats["purchase_scans"] = downloaded
        stats["errors"] += errors
        print(f"  Done: {downloaded} downloaded, {errors} errors")

    def _download_sales_invoices(self, base_dir: Path, stats: Dict):
        """Download all sales invoice PDFs organized by year."""
        print(f"\n{'=' * 60}")
        print("Downloading sales invoice PDFs...")
        print(f"{'=' * 60}")

        invoices = self.client.get_paginated(f"{self.admin_id}/SalesInvoices")
        print(f"  Found {len(invoices)} invoices")

        si_dir = base_dir / "sales_invoice_pdfs"
        si_dir.mkdir(exist_ok=True)

        metadata = []
        downloaded = 0
        errors = 0

        for i, inv in enumerate(invoices, 1):
            inv_id = inv["id"]
            date = inv.get("Date", inv.get("BookDate", ""))
            year = date[:4] if date else "unknown"
            date_short = date[:10] if date else "unknown"
            inv_num = inv.get("InvoiceNumber", inv.get("ReceiptNumber", inv_id))
            description = inv.get("Description", "")

            year_dir = si_dir / year
            year_dir.mkdir(exist_ok=True)

            safe_desc = self._safe_filename(str(description)[:50])
            dest_file = year_dir / f"{date_short}_invoice_{inv_num}_{safe_desc}.pdf"

            if dest_file.exists() and dest_file.stat().st_size > 0:
                metadata.append({
                    "id": inv_id, "invoice_number": inv_num, "date": date,
                    "saved_as": str(dest_file.relative_to(base_dir)),
                    "status": "skipped_exists",
                })
                downloaded += 1
                continue

            content = self.client.download(
                f"{self.admin_id}/SalesInvoices/{inv_id}/Download"
            )

            if content:
                dest_file.write_bytes(content)
                downloaded += 1
                stats["total_bytes"] += len(content)
                metadata.append({
                    "id": inv_id, "invoice_number": inv_num, "date": date,
                    "size_bytes": len(content),
                    "saved_as": str(dest_file.relative_to(base_dir)),
                    "status": "downloaded",
                })
                if i % 100 == 0 or i == len(invoices):
                    print(f"    [{i}/{len(invoices)}] {downloaded} downloaded, {errors} errors")
            else:
                errors += 1
                metadata.append({
                    "id": inv_id, "invoice_number": inv_num, "date": date,
                    "saved_as": None, "status": "error",
                })

        self._save_index(si_dir, "sales_invoice_pdfs", len(invoices),
                         downloaded, errors, metadata)
        stats["sales_pdfs"] = downloaded
        stats["errors"] += errors
        print(f"  Done: {downloaded} downloaded, {errors} errors")

    def _download_offerings(self, base_dir: Path, stats: Dict):
        """Download all offering/quote PDFs."""
        print(f"\n{'=' * 60}")
        print("Downloading offering PDFs...")
        print(f"{'=' * 60}")

        offerings = self.client.get_paginated(f"{self.admin_id}/Offerings")
        print(f"  Found {len(offerings)} offerings")

        off_dir = base_dir / "offering_pdfs"
        off_dir.mkdir(exist_ok=True)

        metadata = []
        downloaded = 0
        errors = 0

        for i, off in enumerate(offerings, 1):
            off_id = off["id"]
            date = off.get("Date", off.get("BookDate", ""))
            date_short = date[:10] if date else "unknown"
            inv_num = off.get("InvoiceNumber", off.get("ReceiptNumber", off_id))
            description = off.get("Description", "")

            safe_desc = self._safe_filename(str(description)[:50])
            dest_file = off_dir / f"{date_short}_offering_{inv_num}_{safe_desc}.pdf"

            if dest_file.exists() and dest_file.stat().st_size > 0:
                metadata.append({
                    "id": off_id, "invoice_number": inv_num, "date": date,
                    "saved_as": str(dest_file.relative_to(base_dir)),
                    "status": "skipped_exists",
                })
                downloaded += 1
                continue

            content = self.client.download(
                f"{self.admin_id}/Offerings/{off_id}/Download"
            )

            if content:
                dest_file.write_bytes(content)
                downloaded += 1
                stats["total_bytes"] += len(content)
                metadata.append({
                    "id": off_id, "invoice_number": inv_num, "date": date,
                    "size_bytes": len(content),
                    "saved_as": str(dest_file.relative_to(base_dir)),
                    "status": "downloaded",
                })
                print(f"    [{i}/{len(offerings)}] {description} - {dest_file.name}")
            else:
                errors += 1
                metadata.append({
                    "id": off_id, "invoice_number": inv_num, "date": date,
                    "saved_as": None, "status": "error",
                })

        self._save_index(off_dir, "offering_pdfs", len(offerings),
                         downloaded, errors, metadata)
        stats["offering_pdfs"] = downloaded
        stats["errors"] += errors
        print(f"  Done: {downloaded} downloaded, {errors} errors")

    def _save_index(self, directory: Path, file_type: str, total: int,
                    downloaded: int, errors: int, items: list):
        """Save a metadata index file for a download category."""
        index_file = directory / "index.json"
        with open(index_file, "w") as f:
            json.dump({
                "type": file_type,
                "count": total,
                "downloaded": downloaded,
                "errors": errors,
                "exported_at": datetime.now().isoformat(),
                "items": items,
            }, f, indent=2, default=str)


def main():
    """CLI entry point for file downloads."""
    _load_env()

    parser = argparse.ArgumentParser(
        description="Download all files from Reeleezee (scans, PDFs, offerings)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --username USER --password PASS
  %(prog)s --username USER --password PASS --output-dir ./files
  %(prog)s  # reads REELEEZEE_USERNAME and REELEEZEE_PASSWORD from .env
        """,
    )
    parser.add_argument(
        "--username",
        default=os.environ.get("REELEEZEE_USERNAME"),
        help="Reeleezee username (or set REELEEZEE_USERNAME env var)",
    )
    parser.add_argument(
        "--password",
        default=os.environ.get("REELEEZEE_PASSWORD"),
        help="Reeleezee password (or set REELEEZEE_PASSWORD env var)",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory (default: exports/files_TIMESTAMP)",
    )

    args = parser.parse_args()

    if not args.username or not args.password:
        print("Error: credentials required.")
        print("Provide --username and --password, or set REELEEZEE_USERNAME")
        print("and REELEEZEE_PASSWORD environment variables (or in a .env file).")
        sys.exit(1)

    if not args.output_dir:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.output_dir = f"exports/files_{timestamp}"

    print(f"{'=' * 60}")
    print("Reeleezee File Downloader")
    print(f"Started: {datetime.now().isoformat()}")
    print(f"Output:  {args.output_dir}")
    print(f"{'=' * 60}")

    from .client import AuthenticationError
    try:
        client = ReeleezeeClient(args.username, args.password)
    except AuthenticationError as e:
        print(f"Error: {e}")
        sys.exit(1)
    downloader = ReeleezeeFileDownloader(client)
    downloader.download_all(args.output_dir)


if __name__ == "__main__":
    main()
